dist: xenial
language: python
python: 3.7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -yq install apt-transport-https

install:
  - wget -qO- https://api.github.com/repos/gohugoio/hugo/releases/latest | sed -r -n '/browser_download_url/{/Linux-64bit.deb/{s@[^:]*:[[:space:]]*"([^"]*)".*@\1@g;p;q}}' | xargs wget
  - sudo dpkg -i hugo*.deb
  - rm -rf public 2> /dev/null

script:
  - hugo
  - mv MASTER-README.md public/README.md
  - echo "$CNAME_URL" > public/CNAME

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  email: $GITHUB_EMAIL
  name: $GITHUB_USERNAME
  verbose: true
  keep-history: true
  local-dir: public
  target_branch: master
  on:
    branch: source
