dist: xenial
language: go
go:
  - master

install:
  - go get github.com/gohugoio/hugo

before_script:
    - rm -rf public 2> /dev/null

script:
  - hugo
  - mv MASTER-README.md public/README.md
  - echo "$CNAME_URL" > public/CNAME

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  email: $GITHUB_EMAIL
  name: $GITHUB_USERNAME
  verbose: true
  keep-history: true
  local-dir: public
  target_branch: master
  on:
    branch: source
