baseURL = "https://imamdigmi.github.io/"
publishDir = "docs"
languageCode = "en"
defaultContentLanguage = "en"
title = "JournalToday"
enableRobotsTXT = true
enableEmoji = true # https://www.webpagefx.com/tools/emoji-cheat-sheet/
theme = "even"

hasCJKLanguage = true
paginate = 3
disqusShortname = "imamdigmi"
googleAnalytics = "UA-74531115-2"
copyright = "imamdigmi"

[author]
  name = "Imam Digmi"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "Categories"
  weight = 40
  identifier = "categories"
  url = "/categories/"

[params]
  debug = false             # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda
  since = "2017"            # Site creation time
  logoTitle = "Imam Digmi"
  keywords = ["imamdigmi", "digmi", "blog", "JournalToday"]
  description = "Belajar adalah cara untuk menghargai waktu."
  archive-paginate = 100
  dateFormatToUse = "Monday, Jan 2, 2006"
  moreMeta = true

  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  comment = true
  toc = true
  autoCollapseToc = false   # Auto expand and collapse toc
  fancybox = true           # see https://github.com/fancyapps/fancybox
  bootcdn = false           # In china. @Deprecated: use [params.publicCDN]
  mathjax = true            # see https://www.mathjax.org/
  mathjaxEnableSingleDollar = false
  linkToMarkDown = false    # if you config contentCopyright and hugo output .md files. #
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'
  changyanAppid = ""        # Changyan app id
  changyanAppkey = ""       # Changyan app key
  livereUID = ""            # LiveRe UID
  baidu_push = false        # baidu push
  baidu_analytics = ""      # Baidu Analytics
  baidu_verification = ""   # Baidu Verification
  google_verification = ""  # Google_Verification

  [params.publicCDN]        # load these files from public cdn
    enable = false
    jquery = '<script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>'
    slideout = '<script src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js" integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>'
    fancyboxJs = '<script src="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.js" integrity="sha256-XVLffZaxoWfGUEbdzuLi7pwaUJv1cecsQJQqGLe7axY=" crossorigin="anonymous"></script>'
    fancyboxCss = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.css" integrity="sha256-7TyXnr2YU040zfSP+rEcz29ggW4j56/ujTPwjMzyqFY=" crossorigin="anonymous">'

  [params.busuanzi]         # count web traffic by busuanzi
    enable = false
    siteUV = true
    sitePV = true
    pagePV = true

  [params.reward]
    enable = false
    wechat = "/path/to/your/wechat-qr-code.png"
    alipay = "/path/to/your/alipay-qr-code.png"

  [params.social]
    a-email = "mailto:imamdigmi@gmail.com"
    b-telegram = "https://t.me/imamdigmi"
    c-linkedin = "https://www.linkedin.com/in/imamdigmi"
    d-github = "https://github.com/imamdigmi/"
    e-stack-overflow = "https://stackoverflow.com/story/imamdigmi"
    f-twitter = "https://twitter.com/imamdigmi/"
    g-facebook = "https://facebook.com/imamdigmi/"
    h-instagram = "https://www.instagram.com/imamdigmi/"

# Uncomment these options to make hugo output .md files.
#[mediaTypes]
#  [mediaTypes."text/plain"]
#    suffix = "md"
#
#[outputFormats.MarkDown]
#  mediaType = "text/plain"
#  isPlainText = true
#  isHTML = false
#
#[outputs]
#  home = ["HTML", "RSS"]
#  page = ["HTML", "MarkDown"]
#  section = ["HTML", "RSS"]
#  taxonomy = ["HTML", "RSS"]
#  taxonomyTerm = ["HTML"]
